# Change these first
owner: JayXTQ
repo: uptime

sites:
  - name: Muusik
    url: https://muusik.app
  - name: Muusik API
    url: https://api.muusik.app
  - name: enka.cards
    url: https://cards.enka.network
  - name: cat-bot
    url: http://catbot.jayxtq.xyz:27000
  - name: dembed
    url: https://dembed.page

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jayxtq.xyz
  # baseUrl: /your-repo-name
  name: Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
